<?php

return [
    ['name' => 'Skopje'],
    ['name' => 'Bitola'],
    ['name' => 'Kumanovo'],
    ['name' => 'Prilep'],
    ['name' => 'Tetovo'],
    ['name' => 'Veles'],
    ['name' => 'Štip'],
    ['name' => 'Ohrid'],
    ['name' => 'Gostivar'],
    ['name' => 'Strumica'],
    ['name' => 'Kavadarci'],
    ['name' => 'Kočani'],
    ['name' => 'Kičevo'],
    ['name' => 'Radoviš'],
    ['name' => 'Sveti Nikole'],
    ['name' => 'Negotino'],
    ['name' => 'Delčevo'],
    ['name' => 'Vinica'],
    ['name' => 'Resen'],
    ['name' => 'Berovo'],
    ['name' => 'Debar'],
    ['name' => 'Kriva Palanka'],
    ['name' => 'Demir Kapija'],
    ['name' => 'Makedonski Brod'],
    ['name' => 'Demir Hisar'],
    ['name' => 'Mavrovo'],
];
